name: Check Exercices

on: [push]

jobs:
  build:
    continue-on-error: true
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint exercices
    - name: Analysing the code
      run: |
        python3 -m unittest discover -v
  
  testing_exercices:
    name: Check code results
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Analysing the code
      run: |
        python3 -m unittest discover -v
